import Mock from "./mock";
import "./__db__/health-beauty";
import "./__db__/shop";
import "./__db__/sales";
import "./__db__/users";
import "./__db__/ticket";
import "./__db__/vendor";
import "./__db__/orders";
import "./__db__/address";
import "./__db__/products";
import "./__db__/dashboard";
Mock.onAny().passThrough();
