const CorporatePurchasing = () => {
    return (
      <div style={{ padding: "2rem", lineHeight: "1.8", fontFamily: "serif" }}>
        <h1 style={{ textAlign: "center", fontWeight: "bold", fontSize: "38pt",  }}>Corporate Purchasing</h1>
        <p>AGCTGAGGAGAGGAGAGGAGAGGAGGAGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGAGGAGGAGGAGGAGGAGGAGGAG</p>
        <p>GAGGAGGAGGAGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGA</p>
        <p>GGAGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAG</p>
        <p>GAGGAGGAGGAGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAG</p>
        <p>GAGGAGGAGGAGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGA</p>
        <p>&nbsp;</p>
        <p>AGCTGAGGAGAGGAGAGGAGAGGAGGAGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGAGGAGGAGGAGGAGGAGGAGGAG</p>
        <p>GAGGAGGAGGAGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGA</p>
        <p>GGAGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAG</p>
        <p>GAGGAGGAGGAGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAG</p>
        <p>GAGGAGGAGGAGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGA</p>
        <p>&nbsp;</p>
        <p>AGCTGAGGAGAGGAGAGGAGAGGAGGAGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGAGGAGGAGGAGGAGGAGGAGGAG</p>
        <p>GAGGAGGAGGAGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGA</p>
        <p>GGAGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAG</p>
        <p>GAGGAGGAGGAGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAG</p>
        <p>GAGGAGGAGGAGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGA</p>
        <p>&nbsp;</p>
        <p>AGCTGAGGAGAGGAGAGGAGAGGAGGAGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGAGGAGGAGGAGGAGGAGGAGGAG</p>
        <p>GAGGAGGAGGAGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGA</p>
        <p>GGAGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAG</p>
        <p>GAGGAGGAGGAGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAG</p>
        <p>GAGGAGGAGGAGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGA</p>
        <p>&nbsp;</p>
      </div>
    );
  };
  
  export default CorporatePurchasing;